wandb_version: 1

hidden_sizes:
  desc: null
  value:
  - 128
  - 128
activation_func:
  desc: null
  value: relu
use_feature_normalization:
  desc: null
  value: true
initialization_method:
  desc: null
  value: orthogonal_
gain:
  desc: null
  value: 0.01
use_naive_recurrent_policy:
  desc: null
  value: false
use_recurrent_policy:
  desc: null
  value: false
recurrent_n:
  desc: null
  value: 1
data_chunk_length:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0005
critic_lr:
  desc: null
  value: 0.0005
opti_eps:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0
std_x_coef:
  desc: null
  value: 1
std_y_coef:
  desc: null
  value: 0.5
critic_epoch:
  desc: null
  value: 5
use_clipped_value_loss:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.2
critic_num_mini_batch:
  desc: null
  value: 1
value_loss_coef:
  desc: null
  value: 1
use_max_grad_norm:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 10.0
use_gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
use_huber_loss:
  desc: null
  value: true
use_policy_active_masks:
  desc: null
  value: true
huber_delta:
  desc: null
  value: 10.0
kl_threshold:
  desc: null
  value: 0.01
ls_step:
  desc: null
  value: 10
accept_ratio:
  desc: null
  value: 0.5
backtrack_coeff:
  desc: null
  value: 0.8
action_aggregation:
  desc: null
  value: prod
share_param:
  desc: null
  value: false
fixed_order:
  desc: null
  value: false
class_ac:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722899654.915068
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.10.8
      5: 0.15.10
      8:
      - 5
